### ISSUE TITLE
Edit Rig has no attribute layers

### ISSUE THREAD

**Issue by ayonmollah** [pKrime/Expy-Kit#55]
Python: Traceback (most recent call last):
  File "C:\Users\ariya\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Expy-Kit-main\operators.py", line 1206, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ariya\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Expy-Kit-main\operators.py", line 1466, in execute
    new_bone.layers[self.ret_bones_layer] = True
    ^^^^^^^^^^^^^^^
AttributeError: 'EditBone' object has no attribute 'layers'

**Comment by Coniix** [comment]
I've experienced similar when trying to bind to active armature and choosing To Bind: Rigify_Controls or Rigify_Controls_0_4 and Bind Target as Mixamo, as soon as I select Mixamo I'm hit with this error.

Am using Blender version 4.2.1, Expy Kit version 0.6.1 and Rigify version 0.6.10

Have been following through the workflow at 21:06 of this video https://www.youtube.com/watch?v=ars_rEC3oP8

And the exact error I get is

Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\Expy-Kit-main\operators.py", line 1466, in execute
    default='None')
                ^^^^
AttributeError: 'EditBone' object has no attribute 'layers'

**Comment by ayonmollah** [comment]
Did you get any Fix though?

**Comment by Coniix** [comment]
Nope not yet just adding further evidence and more details to this issue

**Comment by Coniix** [comment]
Okay I found a way around my issue, basically the problem is I was using blender 4.2, I downgraded to 4.1 and that got me passed the error I was experiencing it.

Until/if proj is updated to support 4.2 I recommend anyone else reading this and experiencing similar problems to try installing 4.1 from Blenders archived versions

**Comment by pKrime** [comment]
Hi,

I can't reproduce this error, basically Expy Kit is running in legacy mode and it's looking for blender's 3 bone layers system. The addon checks bpy.app.version for that, I don't know why it is not registering the right version on your system. Any of you using a custom blender build? I have tested Expy Kit on windows and linux, but not Mac.

**Comment by Coniix** [comment]
I wasn't using a custom build but I just tried to recreate it myself on Blender 4.2 again and seems to be working okay now so I dunno, maybe just some weird one off thing, anyone with similar issues should just try reinstalling or something

**Comment by Hvki-tree** [comment]
Hello, I encountered the same issue, and Blender prompted me with the following message.

**Comment by Hvki-tree** [comment]
I updated the Expy-Kit version to 0.6.1, and the issue has been resolved. Thank you for your work!

**Comment by jvetulani** [comment]
Same errror in Blender 4.4

**Comment by jvetulani** [comment]
Updated operators.py to work with Blender 4.4: 
removed deprecated .layers, fixed bone collections, and wrapped look_bone references.
It works in 4.4 for me now :) This was a bit of a whackamole tho haha :D

[operators.py.zip](https://github.com/user-attachments/files/20717253/operators.py.zip)
